sudo: required
language: generic

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=xenial TRAVIS_DEBIAN_DERIVATIVE=ubuntu
  - TRAVIS_DEBIAN_DISTRIBUTION=bionic TRAVIS_DEBIAN_DERIVATIVE=ubuntu
  - TRAVIS_DEBIAN_DISTRIBUTION=cosmic TRAVIS_DEBIAN_DERIVATIVE=ubuntu

services:
  - docker

script:
  - wget -O- https://raw.githubusercontent.com/KaiHa/travis.debian.net/wip/ubuntu-install-issue/script.sh | sh -

if:
  tag IS blank
