sudo: true
os: linux
dist: xenial
language: cpp

script:
  - ./ci test-stretch

addons:
  apt:
    packages:
    - autopkgtest
    - cowbuilder
    - debhelper
    - debian-archive-keyring
    - devscripts
    - dh-autoreconf
    - fakeroot
    - libvirt-bin
    - libwww-perl
    - lxc
    - pdebuild
