sudo: required
language: generic

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=testing
  - TRAVIS_DEBIAN_DISTRIBUTION=sid
  - TRAVIS_DEBIAN_DISTRIBUTION=bionic TRAVIS_DEBIAN_DERIVATIVE=ubuntu

services:
  - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

if:
  tag IS blank
