sudo: required
language: generic

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=testing
  - TRAVIS_DEBIAN_DISTRIBUTION=sid
  - TRAVIS_DEBIAN_DISTRIBUTION=artful TRAVIS_DEBIAN_DERIVATIVE=ubuntu

services:
  - docker

script:
  - wget -O- https://raw.githubusercontent.com/KaiHa/travis.debian.net/gh-pages/script.sh | sh -

if:
  tag IS blank
