sudo: required
os: linux
dist: xenial
language: generic

env:
  - CPPFLAGS="-std=c++11"
    CXXFLAGS="-std=c++11"
    CFLAGS="-std=c++11"

script:
  - sudo mk-build-deps --install debian/control
  - uscan -ddd
  - tar -x -f ../nix_*.orig.tar.xz --strip-components=1
  - dpkg-buildpackage -us -uc

addons:
  apt:
    packages:
    - autopkgtest
    - debhelper
    - devscripts
    - equivs
    - libwww-perl
