sudo: true
os: linux
dist: xenial
language: cpp

script:
  - apt-cache policy autopkgtest
  - ./ci test-stretch

addons:
  apt:
    packages:
    - autopkgtest/xenial-backports
    - cowbuilder
    - debhelper
    - debian-archive-keyring
    - devscripts
    - dh-autoreconf
    - fakeroot
    - liblxc1/xenial-backports
    - libvirt-bin
    - libwww-perl
    - lxc/xenial-backports
    - lxc-utils/xenial-backports
    - pdebuild
