sudo: required
language: generic

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=stretch
    TRAVIS_DEBIAN_BACKPORTS=stretch-backports

services:
  - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

if:
  tag IS blank
