Document: nix
Title: Debian nix Manual
Author: <insert document author here>
Abstract: This manual describes what nix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nix/nix.sgml.gz

Format: postscript
Files: /usr/share/doc/nix/nix.ps.gz

Format: text
Files: /usr/share/doc/nix/nix.text.gz

Format: HTML
Index: /usr/share/doc/nix/html/index.html
Files: /usr/share/doc/nix/html/*.html
